name: vidyutai
description: AI-Powered Hardware Integration App
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  collection: ^1.18.0
  equatable: ^2.0.7
  http: ^1.2.2
  uuid: ^4.5.1
  logger: ^2.5.0
  # Auth
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  # Bluetooth/WiFi & device discovery
  flutter_blue_plus: ^1.34.5
  network_info_plus: ^6.1.0
  wifi_iot: ^0.3.19
  # Local storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Permissions & device
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  # AI runtimes (placeholders)
  tflite_flutter: ^0.10.4
  onnxruntime: ^1.20.3
  # Media & voice
  camera: ^0.11.0+2
  speech_to_text: ^6.6.2
  flutter_tts: ^4.0.2
  # Charts
  fl_chart: ^0.69.0
  # Notifications
  firebase_messaging: ^15.1.3

  # State utils
  rxdart: ^0.28.0

  # WebSocket client (for Raspberry Pi/ESP APIs)
  web_socket_channel: ^3.0.1

  # Serialization
  retrofit: ^4.4.1
  dio: ^5.7.0

  # Icons
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/
    - assets/icons/
